name = "phoenix-ob1"
main = "reincarnate.js"
compatibility_date = "2024-04-01"
compatibility_flags = ["nodejs_compat"]

[[durable_objects.bindings]]
name = "SESSIONS"
class_name = "SessionDO"

[[migrations]]
tag = "v1-genesis"
new_sqlite_classes = ["SessionDO"]
